<?php 
return array (
  'platform_open' => '1',
  'platform_alipay_open' => '1',
  'platform_alipay_name' => '1967441786@qq.com',
  'platform_alipay_pid' => '2088811313665743',
  'platform_alipay_key' => '3sd8a1d0inqgpmv0li6tlvidsgb35vua',
  'platform_tenpay_open' => '0',
  'platform_tenpay_partnerid' => '',
  'platform_tenpay_partnerkey' => '',
  'platform_tenpayComputer_open' => '0',
  'platform_tenpayComputer_partnerid' => '',
  'platform_tenpayComputer_partnerkey' => '',
  'platform_allinpay_open' => '0',
  'platform_allinpay_merchantId' => '',
  'platform_allinpay_merchantKey' => '',
  'platform_yeepay_open' => '0',
  'platform_yeepay_merchantaccount' => '',
  'platform_yeepay_merchantPrivateKey' => '',
  'platform_yeepay_merchantPublicKey' => '',
  'platform_yeepay_yeepayPublicKey' => '',
  'platform_yeepay_product_catalog' => '',
  'platform_chinabank_open' => '0',
  'platform_chinabank_account' => '',
  'platform_chinabank_key' => '',
);